### ISSUE TITLE
在linux服务器配置出现的问题

### ISSUE THREAD

**Issue by rdone4425** [Akimio521/FastCDN#2]
Traceback (most recent call last):
  File "/root/cdn/main.py", line 95, in <module>
    main()
  File "/root/cdn/main.py", line 21, in main
    email = config_data["setting"]["account"]["email"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Akimio521** [comment]
提示没找到["setting"]["account"]["email"]，你的config文件配置可能有问题，检查一下是不是`:`和邮箱之间没加空格

**Comment by rdone4425** [comment]
email: xxxxx@gmail.com
    global_api_key: 51357aeb37394bdaf72ce55a10461xxxxxx
    zone_id: c6ed8e6f62d70a3464e9e46d8xxxxxx
    这是我在yaml里的文件格式

**Comment by Akimio521** [comment]
缩进有问题，请仔细阅读[config.yaml.example](https://github.com/Akimio521/FastCDN/blob/main/config/config.yaml.example)

**Comment by rdone4425** [comment]
安装示例模板改的

**Comment by Akimio521** [comment]
> email: [xxxxx@gmail.com](mailto:xxxxx@gmail.com)     global_api_key: 51357aeb37394bdaf72ce55a10461xxxxxx     zone_id: c6ed8e6f62d70a3464e9e46d8xxxxxx     这是我在yaml里的文件格式

`email`、`global_api_key`、` zone_id`应该在同一个层级，要么是你复制的时候没复制完整，要么就是你缩进有问题

**Comment by rdone4425** [comment]
setting:
  account:
    email: xxxxx@gmail.com
    global_api_key: 51357aeb37394bdaf72ce55a9046192d93663
    zone_id: c6ed8e6f62d70a3464e4r46d83fd9761
  CFST:
    n: 200  # 延迟测速线程；越多延迟测速越快，但可能会被识别成网络扫描，最多 1000
    t: 4    # 延迟测速次数；单个 IP 延迟测速的次数；(默认 4 次)
    dn: 20  # 下载测速数量；延迟测速并排序后，从最低延迟起下载测速的数量；(默认 10 个)
    dt: 10  # 下载测速时间；单个 IP 下载测速最长时间，不能太短；(默认 10 秒)
    tp: 443 # 指定测速端口；延迟测速/下载测速时使用的端口；(默认 443 端口)
    url: https://cf.xiu2.xyz/url  # 指定测速地址；延迟测速(HTTPing)/下载测速时使用的地址，默认地址不保证可用性，建议自建
    tl: 300 # 平均延迟上限；只输出低于指定平均延迟的 IP，各上下限条件可搭配使用
    tll: 20 # 平均延迟下限；只输出高于指定平均延迟的 IP
    tlr: 0.3  # 丢包几率上限；只输出低于/等于指定丢包率的 IP，范围 0.00~1.00，0 过滤掉任何丢包的 IP；(默认 1.00)
    sl: 3   # 下载速度下限；只输出高于指定下载速度的 IP，凑够指定数量 [-dn] 才会停止测速；(默认 0.00 MB/s)
    麻烦你帮我看看

**Comment by Akimio521** [comment]
`config.yaml`的相对路径是什么

**Comment by rdone4425** [comment]
在linux   /root/cdn/config下

**Comment by Akimio521** [comment]
文件名

**Comment by rdone4425** [comment]
config.yaml

**Comment by Akimio521** [comment]
什么系统版本，我刚刚在Ubuntu 22.04lts上跑通了全流程

**Comment by rdone4425** [comment]
debian11

**Comment by Akimio521** [comment]
Windows和debian的python版本一样吗，版本号是多少

**Comment by Become-ILLUSORY** [comment]
确实存在这个问题，但改用json后解决了
